global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "/opt/prometheus/*.rules.yml"

scrape_configs:
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'prom-rsa'
    static_configs:
      - targets: ['prometheus-rsa:9201']

  - job_name: 'blog'
    static_configs:
      - targets: ['blog:80']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['pg-h.io:8181']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['pg-h.io:9100']

  - job_name: 'pghio'
    static_configs:
      - targets: ['pghio:80']

  - job_name: 'influx'
    static_configs:
      - targets: ['influxdb:8086']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

remote_write:
  - url: "http://prometheus-rsa:9201/write"
    write_relabel_configs:
    - source_labels: [ __name__ ]
      regex: 'ALERTS.*|up.*|clamp_min.*|go_memstats_alloc_bytes.*|go_memstats_alloc_bytes_total.*|go_memstats_next_gc_bytes.*|histogram_quantile.*|http_requests_total.*|label_replace.*|node_cpu_seconds_total.*|node_disk_io_time_seconds_total.*|node_disk_reads_completed_total.*|node_disk_writes_completed_total.*|node_exporter.*|node_filesystem_free_bytes.*|node_filesystem_size_bytes.*|node_memory_Buffers_bytes.*|node_memory_Cached_bytes.*|node_memory_MemFree_bytes.*|node_memory_MemTotal_bytes.*|node_network_receive_bytes_total.*|node_network_transmit_bytes_total.*|pghio_blog_hits_count_total.*|process_cpu_seconds_total.*|process_open_fds.*|process_resident_memory_bytes.*|process_start_time_seconds.*|process_virtual_memory_bytes.*|prometheus_engine_query_duration_seconds.*|prometheus_engine_query_duration_seconds_sum.*|prometheus_local_storage_indexing_queue_length.*|prometheus_local_storage_ingested_samples_total.*|prometheus_local_storage_target_heap_size_bytes.*|prometheus_rule_evaluation_duration_seconds.*|prometheus_rule_evaluation_duration_seconds_count.*|prometheus_rule_evaluation_duration_seconds_sum.*|prometheus_rule_group_.*|prometheus_rule_group_duration_seconds.*|prometheus_rule_group_iterations_missed_total.*|prometheus_rule_group_iterations_total.*|prometheus_target_interval_length_seconds.*|prometheus_target_interval_length_seconds_count.*|prometheus_tsdb_blocks_loaded.*|prometheus_tsdb_compaction_chunk_range_count.*|prometheus_tsdb_compaction_chunk_range_sum.*|prometheus_tsdb_compaction_chunk_samples_count.*|prometheus_tsdb_compaction_chunk_samples_sum.*|prometheus_tsdb_compaction_chunk_size_sum.*|prometheus_tsdb_compaction_duration_bucket.*|prometheus_tsdb_compaction_duration_seconds_sum.*|prometheus_tsdb_compactions_failed_total.*|prometheus_tsdb_compactions_total.*|prometheus_tsdb_compactions_triggered_total.*|prometheus_tsdb_head_active_appenders.*|prometheus_tsdb_head_chunks.*|prometheus_tsdb_head_chunks_created_total.*|prometheus_tsdb_head_chunks_removed_total.*|prometheus_tsdb_head_gc_duration_seconds.*|prometheus_tsdb_head_gc_duration_seconds_count.*|prometheus_tsdb_head_gc_duration_seconds_sum.*|prometheus_tsdb_head_max_time.*|prometheus_tsdb_head_min_time.*|prometheus_tsdb_head_samples_appended_total.*|prometheus_tsdb_head_series.*|prometheus_tsdb_reloads_failures_total.*|prometheus_tsdb_reloads_total.*|prometheus_tsdb_wal_corruptions_total.*|prometheus_tsdb_wal_fsync_duration_seconds_count.*|prometheus_tsdb_wal_fsync_duration_seconds_sum.*|scrape_duration_seconds.*'
      action: keep
