global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "/opt/prometheus/*.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'prom-rsa'
    static_configs:
      - targets: ['prometheus-rsa:9201']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['pg-h.io:8181']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['pg-h.io:9100']

  - job_name: 'influx'
    static_configs:
      - targets: ['influxdb:8086']

remote_write:
  - url: "http://prometheus-rsa:9201/write"
