groups:
- name: up.rules.yml
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      notifyReceiver: email-me
      severity: warning
    annotations:
      summary: "Instance {{$labels.instance}} down"
      description: "{{$labels.instance}} of job {{$labels.job}} has been down for more than 5 minutes."
