version: '2'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/containers/nginx/certs:/opt/certs:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: "json-file"

  pghio:
    image: pghio:latest
    container_name: pghio
    hostname: pghio
    volumes:
      - $PWD/containers/golang_pghio/files/:/opt/pghio/files/:ro
      - $PWD/containers/golang_pghio/html/:/opt/pghio/html/:ro
      - $PWD/containers/golang_pghio/imgs/:/opt/pghio/imgs/:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: "json-file"

  blog:
    image: blog:latest
    container_name: blog
    hostname: blog
    volumes:
      - $PWD/containers/golang_blog/files/:/opt/blog/files/:ro
      - $PWD/containers/golang_blog/imgs/:/opt/blog/imgs/:ro
      - $PWD/containers/golang_blog/posts/:/opt/blog/posts/:ro
      - $PWD/containers/golang_blog/tmpl/:/opt/blog/tmpl/:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: "json-file"

  prometheus:
    image: prom/prometheus:v2.5.0
    container_name: prometheus
    hostname: prometheus
    volumes:
      - $PWD/containers/prometheus/:/opt/prometheus/:ro
      # keep data
      - /data/prometheus/:/prometheus/data/:rw
      - /etc/localtime:/etc/localtime:ro
    command:
      - '--config.file=/opt/prometheus/prometheus.yml'
      # log.level => [debug, info, warn, error]
      - '--log.level=info'
      # prometheus retention period
      - '--storage.tsdb.retention=30d'
    logging:
      driver: "json-file"
    mem_limit: 512m
    memswap_limit: 512m
    restart: unless-stopped
    user: 9090:9090

  alertmanager:
    image: prom/alertmanager:v0.15.3
    container_name: alertmanager
    hostname: alertmanager
    volumes:
      - $PWD/containers/alertmanager/:/opt/alertmanager/:rw
      - /etc/localtime:/etc/localtime:ro
    command:
      - '--config.file=/opt/alertmanager/alertmanager.yml'
      - '--log.level=debug'
    logging:
      driver: "json-file"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:5.4.0
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.pg-h.io
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - /data/grafana/:/var/lib/grafana/:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: "json-file"

  prometheus-rsa:
    image: remote_storage_adapter:latest
    container_name: prometheus-rsa
    hostname: prometheus-rsa
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
    tty: true

  influxdb:
    image: influxdb:1.7.1-alpine
    container_name: influxdb
    hostname: influxdb
    environment:
      - INFLUXDB_HTTP_LOG_ENABLED=false # turn 204 off
      # if you don't want to see the NaN debug warnings, you have to fork the project, hard code to info or make adjustments and submit yet another pull request for this feature
      # - INFLUXDB_DATA_MAX_SERIES_PER_DATABASE=0 # default is 1000000
    volumes:
      - /data/influxdb/:/var/lib/influxdb/
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
    mem_limit: 512m
    memswap_limit: 512m
    restart: unless-stopped
