version: '2'

services:
  nginx:
    image: nginx:1.13.10-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - $PWD/container/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/container/nginx/data/www/:/opt/nginx/data/www/:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: "json-file"

  prometheus:
    image: prom/prometheus:v2.2.1
    container_name: prometheus
    volumes:
      - $PWD/container/prometheus/:/opt/prometheus/:ro
      # keep data
      - /data/prometheus/:/prometheus/data/:rw
      - /etc/localtime:/etc/localtime:ro
    command:
      - '--config.file=/opt/prometheus/prometheus.yml'
      # log.level => [debug, info, warn, error]
      - '--log.level=info'
      # prometheus retention period
      - '--storage.tsdb.retention=30d'
    restart: unless-stopped
    logging:
      driver: "json-file"
    user: 9090:9090

  grafana:
    image: grafana/grafana:5.0.4
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.pg-h.io
    volumes:
      - /data/grafana/:/var/lib/grafana/:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
