global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "/opt/prometheus/*.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'prometheusRemoteStorageAdapter'
    static_configs:
      - targets: ['prometheus-rsa:9201']

remote_write:
  - url: "http://prometheus-rsa:9201/write"
